#!/bin/bash

CMD=$1
FU='/Users/Crazz/Documents/VPNConfig/fu'
LINODE='/Users/Crazz/Documents/VPNConfig/linode'

if [ $CMD == 'fu' ]; then
	sudo cp $FU/ip-* /etc/ppp/
	sudo cp $FU/options /etc/ppp/
	echo 'fu vpn configuration loaded'
elif [ $CMD == 'linode' ]; then
	sudo cp $LINODE/ip-* /etc/ppp/
	sudo cp $LINODE/options /etc/ppp/
	echo 'linode vpn configuration loaded'
fi
